<?php
ini_set('display_errors',true);
require_once 'Swift-5.0.1/lib/swift_required.php';
$body ="<html>
        <center><h3 style='color:blue;'>Confidence</h3></center>
        <p>1) are best You confidence the </p>
        <p>2) Thank very certainty you much</p>
        <p>3) Oh you courage no didn't</p>
        <p>4) want poise I so you </p>
        <p>5) wall on determination the Writing's</p>
        <br>
        <br>
        <br>
        <p style='color:green;'>we are almost getting there Josh :) we are testing and are left with the look and feel</p>
        <p>this email has been generated by the application</p>
        </html>
";
$transport = Swift_SmtpTransport::newInstance('smtp.gmail.com', 465, "ssl")
  ->setUsername('kchaddy871@gmail.com')
  ->setPassword('rungwe01');

$mailer = Swift_Mailer::newInstance($transport);

$message = Swift_Message::newInstance('Daily Questions')
  ->setFrom(array('daily@psycology.com' => 'Psycology Application'))
  ->setTo(array('joshpalfreman@gmail.com'))
  ->setBody($body,'text/html');

$result = $mailer->send($message);

var_dump($result);

function send_questions($to,$body){
    require_once 'Swift-5.0.1/lib/swift_required.php';
    
    $transport = Swift_SmtpTransport::newInstance('smtp.gmail.com', 465, "ssl")
      ->setUsername('kchaddy871@gmail.com')
      ->setPassword('rungwe01');

    $mailer = Swift_Mailer::newInstance($transport);

    $message = Swift_Message::newInstance('Daily Questions')
      ->setFrom(array("kchaddy871@gmail.com" => 'Psycology Application'))
      ->setTo(array($to))
      ->setBody($body,'text/html');

    $result = $mailer->send($message);

    if ($result){
        return TRUE;
    }
    else{
        return FALSE;
    }


    }

?>